/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import org.example.extract.CheckpointManager;
import org.example.extract.CheckpointManagerImpl;
import org.example.extract.CsvExtractorTask;
import org.example.load.OutputFileLoaderTask;
import org.example.transform.ExternalApiClient;
import org.example.transform.ExternalApiClientImpl;
import org.example.transform.ExternalApiTransformerTask;
import org.example.transform.RateLimiter;

public class App {

    public static void main(String[] args) throws InterruptedException {

        File input = new File("./input.csv");
        File output = new File("./output.csv");
        
        //Inizializzazione Code
        int transformQueueCapacity = 5000;
        int writeQueueCapacity = 5000;
        BlockingQueue<String> transformQueue  = new ArrayBlockingQueue<>(transformQueueCapacity);
        BlockingQueue<String> writeQueue = new ArrayBlockingQueue<>(writeQueueCapacity);
        BlockingQueue<String> transformDeadLetterQueue = new ArrayBlockingQueue<>(2000);

        // Stage di Extract

        // Inizializzazione Gestore dei Checkpoint
        File checkpointFile = new File("checkpoint.state");
        CheckpointManager checkpointManager = new CheckpointManagerImpl(checkpointFile);

        String POISON_PILL = "__POISON_PILL__";

        // Creazione del thread per la lettura in streaming da file
        Thread producerThread = new Thread(
                new CsvExtractorTask(input, transformQueue, checkpointManager, POISON_PILL));

        // Stage di Trasform

        // Gestore del rate limiting
        RateLimiter rateLimiter = new RateLimiter(50);

        // Client Api Mock
        ExternalApiClient apiClient = new ExternalApiClientImpl();

        // Creazione Pool di Thread
        int workers = Runtime.getRuntime().availableProcessors() * 2;

        ExecutorService transformerPool = Executors.newFixedThreadPool(workers);

        for (int i = 0; i < workers; i++) {
            transformerPool.submit(new ExternalApiTransformerTask(transformQueue, writeQueue, transformDeadLetterQueue, apiClient, rateLimiter, POISON_PILL)
            );
        }

        // Stage di Load

        //Creazione di Thread per la scrittura dei risultati su file
        Thread writerThread = new Thread(
                new OutputFileLoaderTask(writeQueue, output, POISON_PILL),
                "writer");

        long start = System.currentTimeMillis();

        //Start dei Thread
        producerThread.start();
        writerThread.start();


        //Attesa fine lettura da File
        producerThread.join();
        transformerPool.shutdown();
        transformerPool.awaitTermination(1, TimeUnit.HOURS);

        // chiudi writer
        writeQueue.put(POISON_PILL);
        writerThread.join();

        long end = System.currentTimeMillis();
        System.out.println("Processing completed in " + (end - start) + " ms");
    }
}
